// Shared 3D renderer for the Brass Birmingham table, driven entirely by
// /bb/scene.json (generated by tools/tts-extract/prep-viewer-assets.mjs from
// the TTS save). Three consumers:
//   - the TV main board  (filter: group === 'board')
//   - a player's personal board (filter: group === 'mat:<Color>')
//   - the dev viewer /dev/brass (everything + zone overlay)
//
// Coordinate conventions (hard-won, do not touch casually):
//   - TTS (Unity) is left-handed; three is right-handed. We mirror world Z and
//     negate Y/Z rotations.
//   - OBJ meshes: Unity mirrors X on import, so a local 180-degree Y turn
//     makes their art agree with the mirrored world.
//   - Flat art (tiles, tokens, decks — Unity-native quads): their art must be
//     mirrored across local Z to agree with the mirrored world, or every
//     printed layout (like the player mats) disagrees with piece positions.
//     Implemented as a negative Z scale + DoubleSide materials.

import { Suspense, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { Canvas, useFrame, useLoader, useThree } from '@react-three/fiber';
import { OrbitControls } from '@react-three/drei';
import type { OrbitControls as OrbitControlsImpl } from 'three-stdlib';
import { OBJLoader } from 'three/examples/jsm/loaders/OBJLoader.js';
import { mergeVertices } from 'three/examples/jsm/utils/BufferGeometryUtils.js';
import * as THREE from 'three';

export interface Placement { pos: number[]; rot: number[]; scale: number[]; }
export interface ModelDef { t: 'model'; mesh: string; diffuse: string | null; tint: number[] | null; place: Placement; name: string; group?: string; }
export interface TileDef { t: 'tile'; image: string; back: string | null; aspect?: number; thickness: number; count: number; place: Placement; name: string; group?: string; }
export interface TokenDef { t: 'token'; image: string; aspect?: number; thickness: number; place: Placement; name: string; group?: string; }
export interface DeckDef { t: 'deck'; back: string | null; count: number; place: Placement; name: string; group?: string; }
// A face-up stack of identical cards (the board's wild location / wild industry
// piles): the top shows one cropped cell of the card face sheet.
export interface CardPileDef { t: 'cardpile'; face: string; cols: number; rows: number; cell: number; back: string | null; count: number; place: Placement; name: string; group?: string; }
export interface SimpleDef { t: 'bowl' | 'bag'; tint: number[] | null; place: Placement; name: string; group?: string; }
export type ObjDef = ModelDef | TileDef | TokenDef | DeckDef | CardPileDef | SimpleDef;
export interface Zone { kind: string; name: string; pos: number[]; rot: number[]; scale: number[]; }
export interface CardSheet { image: string; cols: number; rows: number; }
export interface TurnTokenDef { image: string; back: string | null; aspect: number; scale: number; tint: number[] | null; }
export interface CoinDef { mesh: string; diffuse: string | null; aspect?: number; scale: number; }
export interface BarrelDef { mesh: string; diffuse: string; }
export interface SceneDef {
  beerBarrel: BarrelDef;
  board: ModelDef;
  table: ModelDef;
  objects: ObjDef[];
  zones: Zone[];
  cardSheet: CardSheet;
  cardBack: string;
  turnTokens: Record<string, TurnTokenDef>;
  merchantTiles: { cells: Record<string, number>; sheet: { image: string; back: string; cols: number; rows: number } };
  coins: Record<'gold' | 'silver' | 'bronze', CoinDef>;
  cheatSheet?: { image: string; aspect: number };
  actionsSheet?: { image: string; aspect: number };
}

// The subset of the live game state the scene needs to place pieces.
export interface GameSceneState {
  era: 'canal' | 'rail';
  turnOrder: string[];
  merchants: { slot: number; location: string; tile: string; beer: boolean }[];
  drawCount: number;
  colors: string[]; // active player colors
  spentByColor: Record<string, number>; // this round's spending -> coin piles
  industries: Record<string, { color: string; tile: string; flipped: boolean; cubes: number }>; // by square
  links: Record<string, string>; // link name -> color
  markers: { color: string; incomeOffset: number; vpOffset: number }[];
  markets: { coal: number[]; iron: number[] }; // live fill (statics are hidden in-game)
}

export const pos3 = (p: number[]): [number, number, number] => [p[0], p[1], -p[2]];
const deg = THREE.MathUtils.degToRad;
export const rot3 = (r: number[]): THREE.Euler => new THREE.Euler(deg(r[0]), -deg(r[1]), -deg(r[2]), 'YXZ');
const tint3 = (t: number[] | null): THREE.Color =>
  t ? new THREE.Color(t[0], t[1], t[2]) : new THREE.Color('#ffffff');

export const SEAT_COLORS = ['Orange', 'Purple', 'Teal', 'Yellow'] as const;
export const SEAT_HEX: Record<string, string> = {
  Orange: '#e07a4a', Purple: '#8d73cc', Teal: '#5fb8b8', Yellow: '#dcc93e',
  // Rails & Sails seats (Brown is the physical game's black)
  Green: '#4da84f', Red: '#d0483a', Blue: '#3f6fd0', Brown: '#4a4a4a',
  // Trekking adds a white seat
  White: '#e8e6df',
  // Axis & Allies powers (rulebook piece colors)
  germany: '#5a5a5a', ussr: '#7a1f1f', japan: '#d07c28',
  uk: '#b5894e', italy: '#6b4a2b', usa: '#2e7d32',
};

/** Display label for a seat color key (A&A seats are power ids). */
export const SEAT_LABEL: Record<string, string> = {
  germany: 'Germany', ussr: 'Soviet Union', japan: 'Japan',
  uk: 'United Kingdom', italy: 'Italy', usa: 'United States',
};
export const seatLabel = (c: string) => SEAT_LABEL[c] ?? c;

function useColorTexture(url: string) {
  const tex = useLoader(THREE.TextureLoader, url);
  return useMemo(() => {
    tex.colorSpace = THREE.SRGBColorSpace;
    tex.anisotropy = 8;
    return tex;
  }, [tex]);
}

// 1x1 white png: texture fallback for untextured models (tint-only markers),
// so we never point the TextureLoader at a mesh URL.
const WHITE_PX = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==';

function Model({ def }: { def: ModelDef }) {
  const obj = useLoader(OBJLoader, def.mesh);
  const tex = useLoader(THREE.TextureLoader, def.diffuse ?? WHITE_PX);
  const clone = useMemo(() => {
    tex.colorSpace = THREE.SRGBColorSpace;
    tex.anisotropy = 8;
    const c = obj.clone(true);
    c.traverse((o) => {
      const m = o as THREE.Mesh;
      if (!m.isMesh) return;
      // Many of the mod's OBJs ship without vn records; OBJLoader then
      // generates flat normals, which shade round meshes (coins, markers) as
      // hard facets. Merge shared vertices, then recompute smooth normals.
      if (m.geometry) {
        m.geometry.deleteAttribute('normal');
        m.geometry = mergeVertices(m.geometry);
        m.geometry.computeVertexNormals();
      }
      m.material = new THREE.MeshStandardMaterial({
        map: def.diffuse ? tex : null,
        color: tint3(def.tint),
        roughness: 0.8,
        side: THREE.DoubleSide,
      });
    });
    return c;
  }, [obj, tex, def]);
  const p = def.place;
  return (
    <group position={pos3(p.pos)} rotation={rot3(p.rot)} scale={[p.scale[0], p.scale[1], p.scale[2]]}>
      <primitive object={clone} rotation-y={Math.PI} />
    </group>
  );
}

const sideMat = new THREE.MeshStandardMaterial({ color: '#26221c', roughness: 0.9, side: THREE.DoubleSide });

// TTS Custom_Tile sizing by image aspect A = w/h: depth = 2*scale exactly,
// width = 2*scale*A — uniform pixel density, no distortion. (Solved by
// detecting the mat art's slot panels with a dark-region pass and
// least-squares fitting the save's tile positions: 258.0 px/unit horizontal
// vs 261.5 vertical, residuals under 16px. See brass-birmingham memory.)
// Stacks render as one taller box. Face art untinted.
// The double negative scale (-w, -d) rotates the art 180 degrees in-plane,
// which is what the mirrored-world convention requires for flat art to both
// align with piece positions and stay readable (verified against the mat art).
function Tile({ def }: { def: TileDef }) {
  const face = useColorTexture(def.image);
  const back = useColorTexture(def.back ?? def.image);
  const p = def.place;
  const A = def.aspect ?? 1;
  const w = 2 * p.scale[0] * A;
  const d = 2 * p.scale[2];
  const h = 4 * def.thickness * p.scale[1] * def.count;
  const mats = useMemo(() => {
    const top = new THREE.MeshStandardMaterial({ map: face, roughness: 0.85, side: THREE.DoubleSide });
    const bottom = new THREE.MeshStandardMaterial({ map: back, roughness: 0.85, side: THREE.DoubleSide });
    return [sideMat, sideMat, top, bottom, sideMat, sideMat];
  }, [face, back]);
  return (
    <group position={pos3(p.pos)} rotation={rot3(p.rot)}>
      <mesh material={mats} scale={[-w, h, -d]}>
        <boxGeometry />
      </mesh>
    </group>
  );
}

function Token({ def }: { def: TokenDef }) {
  const tex = useColorTexture(def.image);
  const p = def.place;
  const A = def.aspect ?? 1;
  return (
    <group position={pos3(p.pos)} rotation={rot3(p.rot)}>
      <mesh rotation={[-Math.PI / 2, 0, 0]} scale={[-2 * p.scale[0] * A, -2 * p.scale[2], 1]}>
        <planeGeometry />
        <meshStandardMaterial map={tex} transparent alphaTest={0.4} side={THREE.DoubleSide} roughness={0.85} />
      </mesh>
    </group>
  );
}

// Decks sit face down; the visible top is the card back.
function Deck({ def }: { def: DeckDef }) {
  const back = useColorTexture(def.back ?? '');
  const p = def.place;
  const h = Math.max(0.04, def.count * 0.024) * p.scale[1];
  const mats = useMemo(() => {
    const edge = new THREE.MeshStandardMaterial({ color: '#d8d2c2', roughness: 0.95 });
    const backMat = new THREE.MeshStandardMaterial({ map: back, roughness: 0.85, side: THREE.DoubleSide });
    return [edge, edge, backMat, backMat, edge, edge];
  }, [back]);
  return (
    <group position={pos3(p.pos)} rotation={rot3(p.rot)}>
      <mesh material={mats} scale={[-2 * p.scale[0], h, -2.86 * p.scale[2]]}>
        <boxGeometry />
      </mesh>
    </group>
  );
}

// A face-up card pile (wild location / wild industry). Same box as a Deck, but
// the top face shows one cropped cell of the card face sheet instead of a back.
function CardPile({ def }: { def: CardPileDef }) {
  const faceBase = useColorTexture(def.face);
  const back = useColorTexture(def.back ?? def.face);
  const face = useMemo(() => {
    const t = faceBase.clone();
    t.repeat.set(1 / def.cols, 1 / def.rows);
    t.offset.set((def.cell % def.cols) / def.cols, 1 - (Math.floor(def.cell / def.cols) + 1) / def.rows);
    t.needsUpdate = true;
    return t;
  }, [faceBase, def.cols, def.rows, def.cell]);
  const p = def.place;
  const h = Math.max(0.04, def.count * 0.024) * p.scale[1];
  const mats = useMemo(() => {
    const edge = new THREE.MeshStandardMaterial({ color: '#d8d2c2', roughness: 0.95 });
    const faceMat = new THREE.MeshStandardMaterial({ map: face, roughness: 0.85, side: THREE.DoubleSide });
    const backMat = new THREE.MeshStandardMaterial({ map: back, roughness: 0.85, side: THREE.DoubleSide });
    return [edge, edge, faceMat, backMat, edge, edge];
  }, [face, back]);
  return (
    <group position={pos3(p.pos)} rotation={rot3(p.rot)}>
      <mesh material={mats} scale={[-2 * p.scale[0], h, -2.86 * p.scale[2]]}>
        <boxGeometry />
      </mesh>
    </group>
  );
}

// Open bowl: flat base, walls flaring out, slight lip.
const bowlProfile = (() => {
  const pts: THREE.Vector2[] = [
    new THREE.Vector2(0.001, 0.04),
    new THREE.Vector2(0.55, 0.04),
    new THREE.Vector2(0.68, 0.08),
  ];
  for (let i = 1; i <= 8; i++) {
    const t = i / 8;
    pts.push(new THREE.Vector2(0.68 + 0.32 * Math.sin((t * Math.PI) / 2), 0.08 + 0.72 * t));
  }
  pts.push(new THREE.Vector2(1.03, 0.8));
  return pts;
})();

function Bowl({ def }: { def: SimpleDef }) {
  const p = def.place;
  return (
    <group position={pos3(p.pos)} rotation={rot3(p.rot)} scale={[p.scale[0], p.scale[1], p.scale[2]]}>
      <mesh>
        <latheGeometry args={[bowlProfile, 24]} />
        <meshStandardMaterial color={tint3(def.tint)} roughness={0.6} side={THREE.DoubleSide} />
      </mesh>
    </group>
  );
}

// Cloth pouch approximation for TTS built-in bags.
function BagMesh({ def }: { def: SimpleDef }) {
  const p = def.place;
  const color = tint3(def.tint);
  return (
    <group position={pos3(p.pos)} rotation={rot3(p.rot)} scale={[p.scale[0], p.scale[1], p.scale[2]]}>
      <mesh position={[0, 0.55, 0]} scale={[1, 1.05, 1]}>
        <sphereGeometry args={[0.72, 18, 14]} />
        <meshStandardMaterial color={color} roughness={0.95} />
      </mesh>
      <mesh position={[0, 1.45, 0]}>
        <cylinderGeometry args={[0.16, 0.3, 0.5, 12]} />
        <meshStandardMaterial color={color} roughness={0.95} />
      </mesh>
    </group>
  );
}

export function Piece({ def }: { def: ObjDef }) {
  switch (def.t) {
    case 'model': return <Model def={def} />;
    case 'tile': return <Tile def={def} />;
    case 'token': return <Token def={def} />;
    case 'deck': return <Deck def={def} />;
    case 'cardpile': return <CardPile def={def} />;
    case 'bowl': return <Bowl def={def} />;
    case 'bag': return <BagMesh def={def} />;
  }
}

// A flat tile whose art is one cell of a sprite sheet (merchant tiles).
// These sit rotated 180 relative to the tile convention (verified on-board).
function SheetTile({ sheet, cell, size, pos }: {
  sheet: { image: string; cols: number; rows: number }; cell: number; size: number; pos: [number, number, number];
}) {
  const base = useColorTexture(sheet.image);
  const tex = useMemo(() => {
    const t = base.clone();
    t.repeat.set(1 / sheet.cols, 1 / sheet.rows);
    t.offset.set((cell % sheet.cols) / sheet.cols, 1 - (Math.floor(cell / sheet.cols) + 1) / sheet.rows);
    t.needsUpdate = true;
    return t;
  }, [base, sheet, cell]);
  return (
    <group position={pos}>
      <mesh rotation={[-Math.PI / 2, 0, 0]} scale={[size, size, 1]}>
        <planeGeometry />
        <meshStandardMaterial map={tex} roughness={0.85} side={THREE.DoubleSide} />
      </mesh>
    </group>
  );
}

// Round portrait token (the player's profile piece), like the physical game:
// a colored disc with the character portrait on top.
function RoundToken({ tok, color, pos }: { tok: TurnTokenDef; color: string; pos: [number, number, number] }) {
  const base = useColorTexture(tok.image);
  const portrait = useMemo(() => {
    const t = base.clone();
    // clamp edges so minified sampling can't wrap the portrait into streaks,
    // and mipmap for clean minification when the board is zoomed out
    t.wrapS = THREE.ClampToEdgeWrapping;
    t.wrapT = THREE.ClampToEdgeWrapping;
    t.minFilter = THREE.LinearMipmapLinearFilter;
    t.generateMipmaps = true;
    t.needsUpdate = true;
    return t;
  }, [base]);
  const r = tok.scale * 1.7; // token tile was 2*scale wide; scaled up for legibility on the TV board
  const ring = SEAT_HEX[color] ?? '#888';
  return (
    <group position={pos}>
      <mesh position={[0, 0.05, 0]}>
        <cylinderGeometry args={[r, r, 0.1, 32]} />
        <meshStandardMaterial color={ring} roughness={0.6} />
      </mesh>
      {/* portrait clearly above the disc top (0.1) and forced to win the depth
          test — otherwise it z-fights the coloured ring and smears at distance */}
      <mesh position={[0, 0.16, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.88 * 2 * r, 0.88 * 2 * r, 1]}>
        <circleGeometry args={[0.5, 48]} />
        <meshStandardMaterial map={portrait} roughness={0.8} polygonOffset polygonOffsetFactor={-2} polygonOffsetUnits={-2} />
      </mesh>
    </group>
  );
}

// Beer barrel: the real TTS Tileset_Barrel model with its natural brown wood
// texture (the mod tinted it red in TTS; dropped by request).
function BeerBarrel({ def, pos, scale = 1 }: { def: BarrelDef; pos: [number, number, number]; scale?: number }) {
  const obj = useLoader(OBJLoader, def.mesh);
  const tex = useColorTexture(def.diffuse);
  const clone = useMemo(() => {
    const c = obj.clone(true);
    const box = new THREE.Box3().setFromObject(c);
    const size = box.getSize(new THREE.Vector3());
    const s = 0.44 / size.y; // world height ~0.44 on its zone
    c.traverse((o) => {
      const m = o as THREE.Mesh;
      if (!m.isMesh) return;
      m.material = new THREE.MeshStandardMaterial({ map: tex, roughness: 0.85 });
    });
    c.scale.setScalar(s);
    c.position.y = -box.min.y * s;
    return c;
  }, [obj, tex]);
  return (
    <group position={pos} scale={scale}>
      <primitive object={clone} rotation-y={Math.PI} />
    </group>
  );
}

// A pile of coins showing money spent this round: £15 gold, £5 silver, £1 bronze.
function CoinStack({ coins, amount, pos }: { coins: SceneDef['coins']; amount: number; pos: [number, number, number] }) {
  const obj = useLoader(OBJLoader, coins.gold.mesh);
  const gold = useColorTexture(coins.gold.diffuse ?? WHITE_PX);
  const silver = useColorTexture(coins.silver.diffuse ?? WHITE_PX);
  const bronze = useColorTexture(coins.bronze.diffuse ?? WHITE_PX);
  const { geo, height } = useMemo(() => {
    let g: THREE.BufferGeometry | null = null;
    obj.traverse((o) => { const m = o as THREE.Mesh; if (m.isMesh && !g) g = m.geometry; });
    if (!g) return { geo: new THREE.CylinderGeometry(0.3, 0.3, 0.07, 16), height: 0.07 };
    let merged = mergeVertices((g as THREE.BufferGeometry).clone());
    merged.computeVertexNormals();
    merged.computeBoundingBox();
    const bb = merged.boundingBox!;
    return { geo: merged, height: bb.max.y - bb.min.y };
  }, [obj]);
  const mats = useMemo(() => ({
    gold: new THREE.MeshStandardMaterial({ map: gold, roughness: 0.5, metalness: 0.3, side: THREE.DoubleSide }),
    silver: new THREE.MeshStandardMaterial({ map: silver, roughness: 0.5, metalness: 0.3, side: THREE.DoubleSide }),
    bronze: new THREE.MeshStandardMaterial({ map: bronze, roughness: 0.5, metalness: 0.3, side: THREE.DoubleSide }),
  }), [gold, silver, bronze]);

  const pile = useMemo(() => {
    const out: { denom: 'gold' | 'silver' | 'bronze' }[] = [];
    let left = Math.max(0, Math.round(amount));
    while (left >= 15) { out.push({ denom: 'gold' }); left -= 15; }
    while (left >= 5) { out.push({ denom: 'silver' }); left -= 5; }
    while (left >= 1) { out.push({ denom: 'bronze' }); left -= 1; }
    return out;
  }, [amount]);

  let y = 0;
  return (
    <group position={pos}>
      {pile.map((c, i) => {
        const s = coins[c.denom].scale * 0.55;
        const el = (
          <mesh key={i} geometry={geo} material={mats[c.denom]} position={[0, y + (height * s) / 2, 0]} scale={[s, s, s]} rotation-y={i * 0.7} />
        );
        y += height * s * 1.05;
        return el;
      })}
    </group>
  );
}

// The dynamic setup layer: everything the "start script" physically places on
// the board — merchant tiles + beer at the edge markets, the players' portrait
// tokens on the turn-order track, and the shuffled draw deck at its zone.
function SetupPieces({ scene, game }: { scene: SceneDef; game: GameSceneState }) {
  // The board mesh's painted top sits maxY*scaleY above its origin — ~0.181 for
  // this board (local top 10.482 * scale.y 0.01727). Pieces rest on that top; a
  // larger offset floats them (visibly so for the tall beer barrels). Keep a
  // hair above to avoid z-fighting with the board's top face.
  const surfaceY = scene.board.place.pos[1] + 0.184;
  const zone = (kind: string, suffix: string) =>
    scene.zones.find((z) => z.kind === kind && z.name.endsWith(suffix));

  return (
    <>
      {game.merchants.map((m) => {
        const mz = zone('merchantZone', ` merchant ${m.slot}`);
        const bz = zone('merchantBeer', ` beer ${m.slot}`);
        const cell = scene.merchantTiles.cells[m.tile === 'Blank' ? 'Blank' : m.tile];
        return (
          <group key={m.slot}>
            {mz && cell !== undefined && (
              <SheetTile sheet={scene.merchantTiles.sheet} cell={cell} size={mz.scale[0] * 0.92} pos={[mz.pos[0], surfaceY, -mz.pos[2]]} />
            )}
            {m.beer && bz && <BeerBarrel def={scene.beerBarrel} pos={[bz.pos[0], surfaceY, -bz.pos[2]]} />}
          </group>
        );
      })}

      {game.turnOrder.map((color, i) => {
        // The player's barrel (the spent-money bowl) is the prominent barrel on
        // the track; the portrait token sits centered on it, and this round's
        // spent coins pile on the same barrel.
        const bz = zone('spentBowl', `spent ${i + 1}`);
        const tok = scene.turnTokens[color];
        if (!bz || !tok) return null;
        const spent = game.spentByColor[color] ?? 0;
        const at: [number, number, number] = [bz.pos[0], surfaceY, -bz.pos[2]];
        return (
          <group key={color}>
            <RoundToken tok={tok} color={color} pos={at} />
            {spent > 0 && <CoinStack coins={scene.coins} amount={spent} pos={[at[0] + 0.5, at[1] + 0.02, at[2]]} />}
          </group>
        );
      })}

      {(() => {
        const dz = zone('deckZone', 'draw deck');
        if (!dz) return null;
        const def: DeckDef = {
          // Yaw 270 matches the deck zone and the wild piles beside it; the old
          // hardcoded 180 left the draw deck turned 90 degrees off from them.
          t: 'deck', back: scene.cardBack, count: game.drawCount, name: 'draw deck',
          place: { pos: [dz.pos[0], surfaceY + 0.05, dz.pos[2]], rot: [0, 270, 0], scale: [1.12, 1, 1.12] },
        };
        return <Deck def={def} />;
      })()}

      {/* built industries: ONE tile of the player's art on its location square
          (the mat piece may be a stack — force single-tile thickness) */}
      {Object.entries(game.industries).map(([sq, b]) => {
        const z = scene.zones.find((zz) => zz.kind === 'locationSquare' && zz.name === sq);
        const art = scene.objects.find((o): o is TileDef => o.t === 'tile' && o.name === `${b.color} ${b.tile}`);
        if (!z || !art) return null;
        const s = art.place.scale[0];
        const def: TileDef = {
          ...art,
          count: 1,
          image: b.flipped && art.back ? art.back : art.image,
          place: { pos: [z.pos[0], surfaceY + 0.03, z.pos[2]], rot: [0, 180, 0], scale: [s, s, s] },
          name: `${b.color} ${b.tile} (built)`,
        };
        return <Tile key={sq} def={def} />;
      })}

      {/* built links: the owner's canal/railway tile on the connection */}
      {Object.entries(game.links).map(([link, color]) => {
        const z = scene.zones.find((zz) => zz.kind === 'linkZone' && zz.name === link);
        const want = game.era === 'canal' ? 'Canal' : 'Railway';
        const art = scene.objects.find((o): o is TileDef => o.t === 'tile' && o.name === `${color} ${want}`);
        if (!z || !art) return null;
        const def: TileDef = {
          ...art,
          count: 1,
          // zone yaw as-is: the tile art itself already carries the flat-art
          // 180 in the Tile renderer (adding another 180 here flipped them)
          place: { pos: [z.pos[0], surfaceY + 0.02, z.pos[2]], rot: [0, z.rot?.[1] ?? 0, 0], scale: art.place.scale },
          name: `${color} ${want} (built)`,
        };
        return <Tile key={link} def={def} />;
      })}

      {/* live coal/iron markets (statics are hidden in-game) */}
      {(() => {
        const coalDef = scene.objects.find((o): o is ModelDef => o.t === 'model' && o.name === 'Coal');
        const ironDef = scene.objects.find((o): o is ModelDef => o.t === 'model' && o.name === 'Iron');
        return (
          <>
            {coalDef && game.markets.coal.map((v, i) => {
              if (v !== 1) return null;
              const z = zone('coalMarket', `coal ${i}`);
              return z && (
                <Model key={`cm${i}`} def={{ ...coalDef, place: { ...coalDef.place, pos: [z.pos[0], surfaceY + 0.16, z.pos[2]] } }} />
              );
            })}
            {ironDef && game.markets.iron.map((v, i) => {
              if (v !== 1) return null;
              const z = zone('ironMarket', `iron ${i}`);
              return z && (
                <Model key={`im${i}`} def={{ ...ironDef, place: { ...ironDef.place, pos: [z.pos[0], surfaceY + 0.16, z.pos[2]] } }} />
              );
            })}
          </>
        );
      })()}

      {/* resource cubes sitting on built mines / works / breweries */}
      {(() => {
        const coalDef = scene.objects.find((o): o is ModelDef => o.t === 'model' && o.name === 'Coal');
        const ironDef = scene.objects.find((o): o is ModelDef => o.t === 'model' && o.name === 'Iron');
        return Object.entries(game.industries).flatMap(([sq, b]) => {
          if (b.cubes <= 0) return [];
          const z = scene.zones.find((zz) => zz.kind === 'locationSquare' && zz.name === sq);
          if (!z) return [];
          const isCoal = b.tile.startsWith('Coal Mine');
          const isIron = b.tile.startsWith('Iron Works');
          const isBeer = b.tile.startsWith('Brewery');
          if (!isCoal && !isIron && !isBeer) return [];
          const tileTopY = surfaceY + 0.03 + 0.19; // built tile top
          return [...Array(Math.min(b.cubes, 6))].map((_, i) => {
            const col = i % 2;
            const row = Math.floor(i / 2);
            const px = z.pos[0] + (col - 0.5) * 0.4;
            const pz = z.pos[2] + (row - (Math.min(b.cubes, 6) > 2 ? 1 : 0.5)) * 0.36 + 0.18;
            if (isBeer) {
              return <BeerBarrel key={`${sq}-c${i}`} def={scene.beerBarrel} pos={[px, tileTopY, -pz]} scale={0.72} />;
            }
            const def = isCoal ? coalDef : ironDef;
            return def && (
              <Model key={`${sq}-c${i}`} def={{ ...def, place: { ...def.place, pos: [px, tileTopY + 0.1, pz] } }} />
            );
          });
        });
      })()}

      {/* income + VP markers walking the track (statics are hidden in-game) */}
      {game.markers.map((mk, i) => {
        const inc = scene.zones.find((z) => z.kind === 'track' && z.name === `track ${mk.incomeOffset}`);
        const vp = scene.zones.find((z) => z.kind === 'track' && z.name === `track ${((mk.vpOffset % 100) + 100) % 100}`);
        const incDef = scene.objects.find((o): o is ModelDef => o.t === 'model' && o.name === `${mk.color} Income Marker`);
        const vpDef = scene.objects.find((o): o is ModelDef => o.t === 'model' && o.name === `${mk.color} Victory Points`);
        const lift = surfaceY + 0.05 + i * 0.055; // stack co-located markers
        return (
          <group key={mk.color}>
            {inc && incDef && <Model def={{ ...incDef, place: { ...incDef.place, pos: [inc.pos[0], lift, inc.pos[2]] } }} />}
            {vp && vpDef && <Model def={{ ...vpDef, place: { ...vpDef.place, pos: [vp.pos[0], lift, vp.pos[2]] } }} />}
          </group>
        );
      })}
    </>
  );
}

export function useBrassScene(): SceneDef | null {
  const [scene, setScene] = useState<SceneDef | null>(null);
  useEffect(() => {
    fetch('/bb/scene.json').then((r) => r.json()).then(setScene);
  }, []);
  return scene;
}

/** A clickable tap-target on the board or mat (legal move highlight).
 *  Renders as a glowing square matching the printed slot: w/d/rotY from the
 *  zone footprint (r is a legacy fallback -> w = d = 2r). */
export interface PickTarget { id: string; x: number; z: number; r: number; y?: number; w?: number; d?: number; rotY?: number; label?: string; }

/** TV focus request: fly to (x,z), hold, fly back. seq must change per event. */
export interface FocusReq { x: number; z: number; seq: number; }

const FOV = 45;
const FOV_TAN = Math.tan(((FOV / 2) * Math.PI) / 180);

// Deterministically frame the content: straight top-down, centered, at the
// height where it exactly fills the canvas (aspect-aware, so minis fill their
// quadrant and off-origin content like the mats is always in view).
function AimCamera({ cx, cy, cz, hx, hz, controls }: {
  cx: number; cy: number; cz: number; hx: number; hz: number;
  controls: React.RefObject<OrbitControlsImpl | null>;
}) {
  const camera = useThree((s) => s.camera);
  const size = useThree((s) => s.size);
  useEffect(() => {
    const a = size.width / Math.max(1, size.height);
    const h = Math.max(hz / FOV_TAN, hx / (FOV_TAN * a)) * 1.04;
    camera.position.set(cx, cy + h, cz + h * 0.012);
    camera.lookAt(cx, cy, cz);
    const c = controls.current;
    if (c) {
      c.target.set(cx, cy, cz);
      // Lock max zoom-out to the fit framing: this top-down view IS the widest
      // the camera can go (you can only zoom in / pan from here).
      c.maxDistance = h * 1.02;
      c.update();
    }
  }, [camera, size, cx, cy, cz, hx, hz, controls]);
  return null;
}

const easeInOut = (t: number) => t * t * (3 - 2 * t);

// TV event camera: on each new focus seq, glide down to the spot, hold while
// the caption reads, glide home.
function FocusFly({ focus, controls }: { focus?: FocusReq; controls: React.RefObject<OrbitControlsImpl | null> }) {
  const camera = useThree((s) => s.camera);
  const anim = useRef<{
    t: number; fromPos: THREE.Vector3; fromTgt: THREE.Vector3; toPos: THREE.Vector3; toTgt: THREE.Vector3;
  } | null>(null);
  useEffect(() => {
    if (!focus || !controls.current) return;
    anim.current = {
      t: 0,
      fromPos: camera.position.clone(),
      fromTgt: controls.current.target.clone(),
      toPos: new THREE.Vector3(focus.x, 9.5, focus.z + 2.2),
      toTgt: new THREE.Vector3(focus.x, 1.5, focus.z),
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [focus?.seq]);
  useFrame((_, dt) => {
    const a = anim.current;
    const c = controls.current;
    if (!a || !c) return;
    a.t += dt;
    const IN = 1.0, HOLD = 2.8, OUT = 1.0;
    let k: number;
    if (a.t < IN) k = easeInOut(a.t / IN);
    else if (a.t < IN + HOLD) k = 1;
    else if (a.t < IN + HOLD + OUT) k = 1 - easeInOut((a.t - IN - HOLD) / OUT);
    else { anim.current = null; k = 0; }
    camera.position.lerpVectors(a.fromPos, a.toPos, k);
    c.target.lerpVectors(a.fromTgt, a.toTgt, k);
    c.update();
  });
  return null;
}

// Pulsing legal-move square, shaped and rotated like the printed slot.
// A thick square frame (outer 1x1 minus an inner hole) — WebGL line width is
// capped at 1px, so a real border needs geometry, not lineSegments.
const FRAME_GEO = (() => {
  const s = new THREE.Shape();
  s.moveTo(-0.5, -0.5); s.lineTo(0.5, -0.5); s.lineTo(0.5, 0.5); s.lineTo(-0.5, 0.5); s.lineTo(-0.5, -0.5);
  const hole = new THREE.Path();
  const i = 0.4; // inner half -> border band is 0.1 of the unit each side
  hole.moveTo(-i, -i); hole.lineTo(-i, i); hole.lineTo(i, i); hole.lineTo(i, -i); hole.lineTo(-i, -i);
  s.holes.push(hole);
  return new THREE.ShapeGeometry(s);
})();

function PickDisc({ t, onPick }: { t: PickTarget; onPick?: (id: string) => void }) {
  const fill = useRef<THREE.MeshBasicMaterial>(null);
  const frame = useRef<THREE.MeshBasicMaterial>(null);
  const grp = useRef<THREE.Group>(null);
  useFrame(({ clock }) => {
    const k = 0.5 + 0.5 * Math.sin(clock.elapsedTime * 3.6);
    // subtle fill (doesn't flood when many tiles are legal); the bright thick
    // frame is what makes each target clearly readable
    if (fill.current) fill.current.opacity = 0.12 + 0.1 * k;
    if (frame.current) frame.current.opacity = 0.85 + 0.15 * k;
    if (grp.current) grp.current.scale.setScalar(1 + 0.025 * k); // gentle breathe
  });
  const w = t.w ?? t.r * 2;
  const d = t.d ?? t.r * 2;
  const yaw = -((t.rotY ?? 0) * Math.PI) / 180;
  return (
    <group ref={grp} position={[t.x, (t.y ?? 1.72) + 0.06, t.z]} rotation={[0, yaw, 0]}>
      {/* clickable, lightly tinted fill */}
      <mesh
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[w, d, 1]}
        onClick={(e) => { e.stopPropagation(); onPick?.(t.id); }}
        onPointerOver={(e) => { document.body.style.cursor = 'pointer'; e.stopPropagation(); }}
        onPointerOut={() => { document.body.style.cursor = 'auto'; }}
      >
        <planeGeometry />
        <meshBasicMaterial ref={fill} color="#aef7ff" transparent opacity={0.16} depthWrite={false} />
      </mesh>
      {/* thick near-white/cyan frame, ringed OUTSIDE the tile so it separates
          from the mat's printed gold borders — high contrast on both the dark
          map and the gold-and-purple mat */}
      <mesh geometry={FRAME_GEO} rotation={[-Math.PI / 2, 0, 0]} position={[0, 0.02, 0]} scale={[w * 1.18, d * 1.18, 1]}>
        <meshBasicMaterial ref={frame} color="#eaffff" transparent opacity={0.97} depthWrite={false} />
      </mesh>
    </group>
  );
}

export interface TableSceneProps {
  scene: SceneDef;
  /** which object groups to render */
  filter: (group: string) => boolean;
  /** render the board + table meshes (default true) */
  showBoard?: boolean;
  /** initial camera: 'board' frames the main board; 'fit' frames the filtered pieces */
  frame?: 'board' | 'fit';
  /** live game state: renders the setup pieces and hides absent colors */
  game?: GameSceneState;
  /** false = static preview (no controls) for picture-in-picture minis */
  interactive?: boolean;
  /** legal-move tap targets + handler */
  pickTargets?: PickTarget[];
  onPick?: (id: string) => void;
  /** TV: fly the camera to an event location */
  focus?: FocusReq;
  /** extra 3D children (zone markers etc.) */
  children?: ReactNode;
}

export function TableScene({
  scene, filter, showBoard = true, frame = 'board', game, interactive = true,
  pickTargets, onPick, focus, children,
}: TableSceneProps) {
  const controlsRef = useRef<OrbitControlsImpl | null>(null);
  const objects = useMemo(() => {
    let objs = scene.objects.filter((o) => filter(o.group ?? 'board'));
    if (game) {
      // in-game: markers walk the track and the markets change hands, so the
      // static markers and static market cubes are all rendered dynamically
      objs = objs.filter((o) =>
        !/(Income Marker|Victory Points)$/.test(o.name ?? '')
        && !(o.t === 'model' && (o.name === 'Coal' || o.name === 'Iron')));
    }
    return objs;
  }, [scene, filter, game]);

  // Content bounds: the printed board for 'board' frame, the filtered pieces
  // (plus padding) for 'fit'.
  const bounds = useMemo(() => {
    if (frame === 'fit' && objects.length) {
      const box = new THREE.Box3();
      for (const o of objects) box.expandByPoint(new THREE.Vector3(...pos3(o.place.pos)));
      const c = box.getCenter(new THREE.Vector3());
      const size = box.getSize(new THREE.Vector3());
      return { cx: c.x, cy: c.y, cz: c.z, hx: size.x / 2 + 1.4, hz: size.z / 2 + 1.4 };
    }
    return { cx: 0, cy: 1.3, cz: 0, hx: 12.0, hz: 12.0 };
  }, [frame, objects]);

  return (
    // near 0.5 (not the 0.1 default): the painted board floats only 0.03 above
    // the dark table slab, and with the camera 30-90 units out the default near
    // plane leaves too little depth precision to separate them — the table
    // z-fights through the board as black flicker while zooming.
    <Canvas camera={{ fov: FOV, position: [bounds.cx, 40, bounds.cz], near: 0.5, far: 400 }} gl={{ antialias: true }}>
      <ambientLight intensity={0.85} />
      <directionalLight position={[10, 30, 10]} intensity={1.4} />
      <directionalLight position={[-15, 20, -10]} intensity={0.5} />
      <Suspense fallback={null}>
        {showBoard && <Model def={scene.table} />}
        {showBoard && <Model def={scene.board} />}
        {objects.map((o, i) => <Suspense key={i} fallback={null}><Piece def={o} /></Suspense>)}
        {game && showBoard && <Suspense fallback={null}><SetupPieces scene={scene} game={game} /></Suspense>}
      </Suspense>
      {pickTargets?.map((t) => <PickDisc key={t.id} t={t} onPick={onPick} />)}
      {children}
      {/* Interaction: click-drag pans, wheel/pinch zooms, right-drag orbits. */}
      <OrbitControls
        ref={controlsRef}
        enabled={interactive}
        mouseButtons={{ LEFT: THREE.MOUSE.PAN, MIDDLE: THREE.MOUSE.DOLLY, RIGHT: THREE.MOUSE.ROTATE }}
        touches={{ ONE: THREE.TOUCH.PAN, TWO: THREE.TOUCH.DOLLY_PAN }}
        maxPolarAngle={Math.PI / 2.05}
        minDistance={3}
        maxDistance={90}
      />
      <AimCamera {...bounds} controls={controlsRef} />
      <FocusFly focus={focus} controls={controlsRef} />
    </Canvas>
  );
}
